begin;

create table if not exists public.rooms (
    id bigint generated by default as identity primary key,
    owner_id uuid not null default auth.uid()
        references auth.users(id) on delete cascade,
    name text not null check (char_length(name) between 1 and 100),
    created_at timestamptz not null default now()
);

create unique index if not exists rooms_owner_name_key
    on public.rooms (owner_id, lower(name));

create table if not exists public.courses (
    id bigint generated by default as identity primary key,
    owner_id uuid not null default auth.uid()
        references auth.users(id) on delete cascade,
    name text not null check (char_length(name) between 1 and 100),
    created_at timestamptz not null default now()
);

create unique index if not exists courses_owner_name_key
    on public.courses (owner_id, lower(name));

create table if not exists public.class_sessions (
    id text primary key,
    owner_id uuid not null default auth.uid()
        references auth.users(id) on delete cascade,
    name text not null check (char_length(name) between 1 and 120),
    room_id bigint references public.rooms(id) on delete set null,
    course_id bigint references public.courses(id) on delete set null,
    source_type text not null
        check (source_type in ('video', 'webcam')),
    source_label text,
    video_object_path text,
    recording_started_at timestamptz not null,
    created_at timestamptz not null default now(),
    ended_at timestamptz,
    status text not null default 'active'
        check (status in ('active', 'completed', 'failed', 'cancelled'))
);

create table if not exists public.analysis_jobs (
    id uuid primary key default gen_random_uuid(),
    owner_id uuid not null default auth.uid()
        references auth.users(id) on delete cascade,
    session_id text not null unique
        references public.class_sessions(id) on delete cascade,
    status text not null default 'queued'
        check (status in (
            'queued', 'processing', 'completed', 'failed', 'cancelled'
        )),
    progress smallint not null default 0
        check (progress between 0 and 100),
    attempt_count integer not null default 0
        check (attempt_count >= 0),
    worker_id text,
    error_message text,
    result_summary jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    started_at timestamptz,
    completed_at timestamptz
);

create table if not exists public.session_tracks (
    session_id text not null
        references public.class_sessions(id) on delete cascade,
    track_id integer not null check (track_id > 0),
    first_seen_seconds double precision not null
        check (first_seen_seconds >= 0),
    last_seen_seconds double precision not null
        check (last_seen_seconds >= 0),
    visible_seconds double precision not null
        check (visible_seconds >= 0),
    attention_rate double precision not null
        check (attention_rate between 0 and 100),
    current_behavior text not null,
    behavior_seconds jsonb not null default '{}'::jsonb,
    event_counts jsonb not null default '{}'::jsonb,
    active boolean not null default false,
    primary key (session_id, track_id)
);

create table if not exists public.behavior_events (
    session_id text not null,
    track_id integer not null,
    event_index integer not null check (event_index >= 0),
    behavior text not null,
    start_seconds double precision not null check (start_seconds >= 0),
    end_seconds double precision not null check (end_seconds >= 0),
    duration_seconds double precision not null
        check (duration_seconds >= 0),
    avg_confidence double precision not null
        check (avg_confidence between 0 and 100),
    primary key (session_id, track_id, event_index),
    foreign key (session_id, track_id)
        references public.session_tracks(session_id, track_id)
        on delete cascade
);

create table if not exists public.evidence_images (
    session_id text not null,
    track_id integer not null,
    evidence_key text not null,
    event_index integer,
    kind text not null check (kind in ('reference', 'event')),
    behavior text not null,
    captured_seconds double precision not null
        check (captured_seconds >= 0),
    filename text not null,
    storage_path text not null,
    width integer not null check (width > 0),
    height integer not null check (height > 0),
    file_size bigint not null check (file_size >= 0),
    created_at timestamptz not null default now(),
    primary key (session_id, track_id, evidence_key),
    foreign key (session_id, track_id)
        references public.session_tracks(session_id, track_id)
        on delete cascade
);

create table if not exists public.track_time_buckets (
    session_id text not null,
    track_id integer not null,
    bucket_start_seconds double precision not null
        check (bucket_start_seconds >= 0),
    visible_seconds double precision not null
        check (visible_seconds >= 0),
    behavior_seconds jsonb not null default '{}'::jsonb,
    event_counts jsonb not null default '{}'::jsonb,
    primary key (session_id, track_id, bucket_start_seconds),
    foreign key (session_id, track_id)
        references public.session_tracks(session_id, track_id)
        on delete cascade
);

create index if not exists class_sessions_owner_created_idx
    on public.class_sessions(owner_id, created_at desc);
create index if not exists class_sessions_room_course_idx
    on public.class_sessions(room_id, course_id);
create index if not exists analysis_jobs_status_created_idx
    on public.analysis_jobs(status, created_at);
create index if not exists behavior_events_session_time_idx
    on public.behavior_events(session_id, start_seconds);
create index if not exists evidence_images_session_time_idx
    on public.evidence_images(session_id, captured_seconds);
create index if not exists track_time_buckets_session_time_idx
    on public.track_time_buckets(session_id, bucket_start_seconds);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger analysis_jobs_set_updated_at
before update on public.analysis_jobs
for each row execute function public.set_updated_at();

alter table public.rooms enable row level security;
alter table public.courses enable row level security;
alter table public.class_sessions enable row level security;
alter table public.analysis_jobs enable row level security;
alter table public.session_tracks enable row level security;
alter table public.behavior_events enable row level security;
alter table public.evidence_images enable row level security;
alter table public.track_time_buckets enable row level security;

create policy rooms_owner_access on public.rooms
for all to authenticated
using (owner_id = (select auth.uid()))
with check (owner_id = (select auth.uid()));

create policy courses_owner_access on public.courses
for all to authenticated
using (owner_id = (select auth.uid()))
with check (owner_id = (select auth.uid()));

create policy class_sessions_owner_access on public.class_sessions
for all to authenticated
using (owner_id = (select auth.uid()))
with check (
    owner_id = (select auth.uid())
    and (
        room_id is null
        or exists (
            select 1
            from public.rooms
            where rooms.id = class_sessions.room_id
              and rooms.owner_id = (select auth.uid())
        )
    )
    and (
        course_id is null
        or exists (
            select 1
            from public.courses
            where courses.id = class_sessions.course_id
              and courses.owner_id = (select auth.uid())
        )
    )
);

create policy analysis_jobs_owner_access on public.analysis_jobs
for all to authenticated
using (owner_id = (select auth.uid()))
with check (
    owner_id = (select auth.uid())
    and exists (
        select 1
        from public.class_sessions
        where class_sessions.id = analysis_jobs.session_id
          and class_sessions.owner_id = (select auth.uid())
    )
);

create policy session_tracks_owner_read on public.session_tracks
for select to authenticated
using (
    exists (
        select 1
        from public.class_sessions
        where class_sessions.id = session_tracks.session_id
          and class_sessions.owner_id = (select auth.uid())
    )
);

create policy behavior_events_owner_read on public.behavior_events
for select to authenticated
using (
    exists (
        select 1
        from public.class_sessions
        where class_sessions.id = behavior_events.session_id
          and class_sessions.owner_id = (select auth.uid())
    )
);

create policy evidence_images_owner_read on public.evidence_images
for select to authenticated
using (
    exists (
        select 1
        from public.class_sessions
        where class_sessions.id = evidence_images.session_id
          and class_sessions.owner_id = (select auth.uid())
    )
);

create policy track_time_buckets_owner_read on public.track_time_buckets
for select to authenticated
using (
    exists (
        select 1
        from public.class_sessions
        where class_sessions.id = track_time_buckets.session_id
          and class_sessions.owner_id = (select auth.uid())
    )
);

grant usage on schema public to authenticated;
grant select, insert, update, delete
    on public.rooms, public.courses, public.class_sessions
    to authenticated;
grant select, insert on public.analysis_jobs to authenticated;
grant select
    on public.session_tracks,
       public.behavior_events,
       public.evidence_images,
       public.track_time_buckets
    to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (id, name, public, allowed_mime_types)
values (
    'class-videos',
    'class-videos',
    false,
    array[
        'video/mp4',
        'video/quicktime',
        'video/webm',
        'video/x-matroska',
        'video/x-msvideo'
    ]
)
on conflict (id) do update set
    public = excluded.public,
    allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, allowed_mime_types)
values (
    'class-evidence',
    'class-evidence',
    false,
    array['image/jpeg']
)
on conflict (id) do update set
    public = excluded.public,
    allowed_mime_types = excluded.allowed_mime_types;

create policy class_videos_owner_insert on storage.objects
for insert to authenticated
with check (
    bucket_id = 'class-videos'
    and (storage.foldername(name))[1] = (select auth.uid()::text)
);

create policy class_videos_owner_read on storage.objects
for select to authenticated
using (
    bucket_id = 'class-videos'
    and (storage.foldername(name))[1] = (select auth.uid()::text)
);

create policy class_videos_owner_update on storage.objects
for update to authenticated
using (
    bucket_id = 'class-videos'
    and (storage.foldername(name))[1] = (select auth.uid()::text)
)
with check (
    bucket_id = 'class-videos'
    and (storage.foldername(name))[1] = (select auth.uid()::text)
);

create policy class_videos_owner_delete on storage.objects
for delete to authenticated
using (
    bucket_id = 'class-videos'
    and (storage.foldername(name))[1] = (select auth.uid()::text)
);

create policy class_evidence_owner_read on storage.objects
for select to authenticated
using (
    bucket_id = 'class-evidence'
    and (storage.foldername(name))[1] = (select auth.uid()::text)
);

create policy class_evidence_owner_delete on storage.objects
for delete to authenticated
using (
    bucket_id = 'class-evidence'
    and (storage.foldername(name))[1] = (select auth.uid()::text)
);

commit;
